adminlte/Controllers/TASEstudianteController.cs
using adminlte.TASEstudianteMateriasAsignacionService;
using adminlte.TASEstudianteService;
using adminlte.TASGrupoService;
using adminlte.TASMateriaService;
using adminlte.TASProgramaService;
using adminlte.TASRegistroNotasService;
using CrystalDecisions.CrystalReports.Engine;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace adminlte.Controllers
{
    public class TASEstudianteController : BaseController
    {
        // GET: TASEstudiante
        public ActionResult TASEstudianteLista()
        {
            TASEstudianteInterfaceClient TASEstudiante = new TASEstudianteInterfaceClient();
            var ltTASEstudiante = TASEstudiante.WebTASEstudianteSeleccionarTodo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            return View(ltTASEstudiante);
        }

        [HttpGet]
        public ActionResult TASEstudianteNuevo(string MensajeError = "")
        {
            TASEstudianteInterfaceClient TASEstudiante = new TASEstudianteInterfaceClient();
            TASEstudianteSet setTASEstudiante = TASEstudiante.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);
            //List<TASEstudianteEntity> ltTASEstudiante = TASEstudiante.WebTASEstudianteSeleccionarXSubCompania((string)Session["SesionSubCompania"], (string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            TASProgramaInterfaceClient TASPrograma = new TASProgramaInterfaceClient();
            List<TASProgramaEntity> ltTASPrograma = TASPrograma.WebTASProgramaSeleccionarXSubCompania((string)Session["SesionSubCompania"], (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
            ViewBag.ltTASPrograma = ltTASPrograma.Select(s => s.Programa).ToList();

            TASGrupoInterfaceClient TASGrupo = new TASGrupoInterfaceClient();
            List<TASGrupoEntity> ltTASGrupo = TASGrupo.WebTASGrupoSeleccionarXSubCompania((string)Session["SesionSubCompania"], (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
            ViewBag.ltTASGrupo = ltTASGrupo.Select(s => s.Grupo).ToList();

            var ltSexo = new SelectList(
                   new List<ListItem>
                   {
                        new ListItem { Text = "Femenino", Value = "F" },
                        new ListItem { Text = "Masculino", Value = "M"},
                   }, "Value", "Text");
            ViewBag.ltSexo = ltSexo;

            var ltVacunaAntitetanica = new SelectList(
                   new List<ListItem>
                   {
                        new ListItem { Text = "En Progreso", Value = "1" },
                        new ListItem { Text = "Completa", Value = "2"},
                   }, "Value", "Text");
            ViewBag.ltVacunaAntitetanica = ltVacunaAntitetanica;

            var ltExamenPsifisiologico = new SelectList(
                   new List<ListItem>
                   {
                        new ListItem { Text = "Habilitada", Value = "1" },
                        new ListItem { Text = "No Habilitada", Value = "2"},
                   }, "Value", "Text");
            ViewBag.ltExamenPsifisiologico = ltExamenPsifisiologico;

            var ltSiNo = new SelectList(
                   new List<ListItem>
                   {
                        new ListItem { Text = "Si", Value = "1" },
                        new ListItem { Text = "No", Value = "2"},
                   }, "Value", "Text");
            ViewBag.ltSiNo = ltSiNo;

            ViewBag.MensajeError = MensajeError;

            return View(setTASEstudiante);
        }

        [HttpPost]
        public ActionResult TASEstudianteNuevo(TASEstudianteSet setTASEstudiante, 
            string Sexo, string VacunaAntitetanica, string ExamenPsicofisiologico, string InstruccionPrevia, string ExperienciaPrevia)
        {
            long NumError = 0;
            string EstudianteCI = string.Empty;
            string MensajeError = string.Empty;

            TASEstudianteInterfaceClient TASEstudiante = new TASEstudianteInterfaceClient();

            if (setTASEstudiante.ltTASEstudiante != null)
            {
                TASEstudianteEntity etTASEstudiante = setTASEstudiante.ltTASEstudiante.First();
                if (etTASEstudiante.Grupo == null || etTASEstudiante.Grupo == "")
                {
                    NumError = 1;
                    MensajeError += "Debe seleccionar un Grupo. ";
                }
                
                if(etTASEstudiante.Programa == null || etTASEstudiante.Programa == "")
                {
                    NumError = 1;
                    MensajeError += "Debe seleccionar un Programa. ";
                }
                
                //if (etTASEstudiante.Sexo == null || etTASEstudiante.Sexo == "")
                //{
                //    NumError = 1;
                //    MensajeError = "Debe seleccionar el campo Sexo. ";
                //}

                if (etTASEstudiante.EstudianteCI == null || etTASEstudiante.EstudianteCI == "")
                {
                    NumError = 1;
                    MensajeError += "Debe ingresar el CI del estudiante. ";
                }

                //if (etTASEstudiante.EstadoCivil == null || etTASEstudiante.EstadoCivil == "")
                //{
                //    NumError = 1;
                //    MensajeError = "Debe seleccionar el campo EstadoCivil.";
                //}


                //if (etTASEstudiante.Sexo == null || etTASEstudiante.Sexo == "")
                //{
                //    NumError = 1;
                //    MensajeError = "Debe llenar el campo CodigoTAS.";
                //}

                if (VacunaAntitetanica == null || VacunaAntitetanica == "")
                {
                    NumError = 1;
                    MensajeError += "Debe llenar el campo Vacuna Antitetanica.";
                }

                if (VacunaAntitetanica == null || VacunaAntitetanica == "")
                {
                    NumError = 1;
                    MensajeError += "Debe llenar el campo Vacuna Antitetanica.";
                }

                if (ExamenPsicofisiologico == null || ExamenPsicofisiologico == "")
                {
                    NumError = 1;
                    MensajeError += "Debe llenar el campo Examen Psicofisiologico.";
                }

                if (InstruccionPrevia == null || InstruccionPrevia == "")
                {
                    NumError = 1;
                    MensajeError += "Debe llenar el campo Instruccion Previa.";
                }

                if (ExperienciaPrevia == null || ExperienciaPrevia == "")
                {
                    NumError = 1;
                    MensajeError += "Debe llenar el campo Experiencia Previa.";
                }

                if (NumError == 0)
                {
                    TASEstudianteSet setTASEstudianteNuevo = TASEstudiante.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                    TASEstudianteEntity etTASEstudianteNuevo = setTASEstudianteNuevo.ltTASEstudiante.First();
                    etTASEstudianteNuevo.SubCompania = (string)Session["SesionSubCompania"];
                    etTASEstudianteNuevo.EstudianteCI = etTASEstudiante.EstudianteCI == null ? "" : etTASEstudiante.EstudianteCI;
                    etTASEstudianteNuevo.Programa = etTASEstudiante.Programa == null ? "" : etTASEstudiante.Programa;
                    etTASEstudianteNuevo.Grupo = etTASEstudiante.Grupo == null ? "" : etTASEstudiante.Grupo;
                    //CodigoTAS Same as EstudianteCI
                    etTASEstudianteNuevo.CodigoTAS = etTASEstudiante.EstudianteCI == null ? "" : etTASEstudiante.EstudianteCI;
                    etTASEstudianteNuevo.Fecha = etTASEstudiante.Fecha;
                    etTASEstudianteNuevo.Nombre1 = etTASEstudiante.Nombre1 == null ? "" : etTASEstudiante.Nombre1;
                    etTASEstudianteNuevo.Nombre2 = etTASEstudiante.Nombre2 == null ? "" : etTASEstudiante.Nombre2;
                    etTASEstudianteNuevo.Apellido1 = etTASEstudiante.Apellido1 == null ? "" : etTASEstudiante.Apellido1;
                    etTASEstudianteNuevo.Apellido2 = etTASEstudiante.Apellido2 == null ? "" : etTASEstudiante.Apellido2;
                    etTASEstudianteNuevo.LugarNacimiento = etTASEstudiante.LugarNacimiento == null ? "" : etTASEstudiante.LugarNacimiento;
                    etTASEstudianteNuevo.Sexo = Sexo == null ? "" : Sexo;
                    etTASEstudianteNuevo.FechaNacimiento = etTASEstudiante.FechaNacimiento;
                    etTASEstudianteNuevo.Nacionalidad = etTASEstudiante.Nacionalidad == null ? "" : etTASEstudiante.Nacionalidad;
                    etTASEstudianteNuevo.EstadoCivil = etTASEstudiante.EstadoCivil == null ? "" : etTASEstudiante.EstadoCivil;
                    etTASEstudianteNuevo.Domicilio = etTASEstudiante.Domicilio == null ? "" : etTASEstudiante.Domicilio;
                    etTASEstudianteNuevo.Telefono = etTASEstudiante.Telefono == null ? "" : etTASEstudiante.Telefono;
                    etTASEstudianteNuevo.Celular = etTASEstudiante.Celular == null ? "" : etTASEstudiante.Celular;
                    etTASEstudianteNuevo.TelefonoFamiliar = etTASEstudiante.TelefonoFamiliar == null ? "" : etTASEstudiante.TelefonoFamiliar;
                    etTASEstudianteNuevo.Correo = etTASEstudiante.Correo == null ? "" : etTASEstudiante.Correo;
                    etTASEstudianteNuevo.NombrePadre = etTASEstudiante.NombrePadre == null ? "" : etTASEstudiante.NombrePadre;
                    etTASEstudianteNuevo.CelularPadre = etTASEstudiante.CelularPadre == null ? "" : etTASEstudiante.CelularPadre;
                    etTASEstudianteNuevo.NombreTutor = etTASEstudiante.NombreTutor == null ? "" : etTASEstudiante.NombreTutor;

adminlte/Views/TASEstudiante/TASEstudianteAsignacionMaterias.cshtml
@{
    ViewBag.Title = "TASEstudianteAsignacionMaterias";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Asignar Materias</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Asignar Materias</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div id="msjContainer"></div>
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Asignar Materias</h3>
                <div class="box-tools pull-right">
                    @*<button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fa fa-times"></i>
                            </button>*@
                </div>
            </div>
            <div class="box-body">
                <div class="col-xs-12 text-center form-group">
                    @Html.DropDownList("ltTASGrupo", new SelectList(@ViewBag.ltTASGrupo as System.Collections.IEnumerable), "Seleccione un grupo", new { @class = "form-control", @onchange = "LlenarEstudiantes()" })
                </div>

                <form action="@Url.Action("TASEstudianteAsignacionMaterias","TASEstudiante")" method="post">
                    <div class="col-xs-12 text-center form-group">
                        @*@Html.DropDownList("Estudiante", new SelectList(@ViewBag.ltAXFUsuarioClaseUsuario as System.Collections.IEnumerable), "Seleccione un estudiante", new { @class = "form-control" })*@

                        @Html.DropDownList("Estudiante", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="col-xs-12 text-center">
                        <button type="submit" class="btn btn-default btn-default">Gestionar</button>
                    </div>
                </form>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">

            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@section scripts
{

    <script type="text/javascript">

        $(document).ready(function () {
        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null ) {
            if (MensajeError != "") {
                muestraMesanje(3,MensajeError);
            }
        }
            @*var url = '@Url.Action("AdminMensualidadGestionEstudiante", "AdminMensualidad", new { Estudiante = "-----" })'
            $('.linkgestionar').on('click', function () {
                alert("asdasd");
                url = url.replace("-----", $('#Estudiante').val());
                window.location = url;
            });*@
    });

    function muestraMesanje(tipo, msj) {

        $("#msjContainer").html('');

        if (tipo == 1) {
            $("#msjContainer").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainer").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainer").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

        }

        function LlenarEstudiantes() {

            var Grupo = $('#ltTASGrupo').val();
            //console.log(CategoryId);

            $.ajax({
                url: 'ObtenerEstudiantesGrupo',
                type: "GET",
                dataType: "JSON",
                data: { Grupo: Grupo },
                success: function (response) {
                    //console.log(response);
                    $("#Estudiante").html("");
                    $.each(response.ltTASEstudiante, function (index, value) {
                        $("#Estudiante").append(
                            $('<option></option>').val(value.EstudianteCI).html(value.Nombre1 + ' ' + value.Apellido1 + ' - ' + value.EstudianteCI));
                    });
                }
            });
        }

    </script>

}

adminlte/Views/TASEstudiante/TASEstudianteAsignacionMateriasEstudiante.cshtml
@model List<adminlte.TASEstudianteMateriasAsignacionService.TASEstudianteMateriasAsignacionEntity>


@{
    ViewBag.Title = "TASEstudianteMateriasAsignacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebGrid grid = new WebGrid(Model, // source
                                null, // columnNames
                                null, // defaultSort
                                80,   // rowsPerPage
                                true, // canPage
                                true, // canSort
                                null, // ajaxUpdateContainerId
                                null, // ajaxUpdateCallback
                                null, // fieldNamePrefix
                                null, // pageFieldName
                                null, // selectionFieldName
                                null, // sortFieldName
                                null);// sortDirectionFieldName
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Asignar Materias</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Asignar Materias</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content table-responsive">
        <!-- Default box -->
        <div class="box box-primary">
            <div id="msjContainer"></div>
            <div class="box-header with-border">
                <h3 class="box-title">CIAC TAS</h3>
            </div>
            <!-- /.box-header -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @*<form action="@Url.Action("TASEstudianteMateriasAsignacionGestionEstudiante","TASEstudianteMateriasAsignacion", new {ltTASEstudianteMateriasAsignacionDetalle = Model })" method="post" role="form">*@

                <div class="col-sm-12">
                    @Html.ActionLink(" ", "TASEstudianteAsignacionMaterias", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>

                <div class="form-group">
                    @*@Html.Label("Cantidad Preguntas")*@
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-users"> @Html.Label((string)ViewBag.EstudianteCI, new { htmlAttributes = new { @class = "form-control" } })</i>
                        </div>
                    </div>
                    <!-- /.input group -->
                </div>

                <div class="box-body">
                    <p>
                        @Html.ActionLink(" ", "TASEstudianteAsignacionMateriasEstudianteNuevo", new { EstudianteCI = (string)ViewBag.EstudianteCI }, new { data_modal = "", @class = "glyphicon glyphicon-plus ", style = "font-size:20px;" })
                    </p>
                    <br />
                    @grid.GetHtml(
                        tableStyle: "table table-bordered",
                        headerStyle: "header",
                        alternatingRowStyle: "alt",
                        //tableStyle: "gridtable",
                        //headerStyle: "gridtable-header",
                        //alternatingRowStyle: "gridtable-alt",
                        footerStyle: "table-pager-footer",
                        columns: new[] {
                            //grid.Column("TipoDoc"),
                           // grid.Column("SubCompania"),
                            grid.Column("Grupo"),
                            grid.Column("Materia"),
                            //grid.Column("Estado"),
                        })
                </div>
            }
            @*</form>*@

        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content" style="padding-top:2%;">
            <div id='myModalContent' style="padding-left:5%;"></div>
        </div>
    </div>
</div>

<script src="~/Scripts/adminlte/components/jquery/dist/jquery.min.js"></script>
<script src="~/Scripts/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="~/Scripts/adminlte/js/modal.js"></script>

@section scripts
{
<script type="text/javascript">

     $(document).ready(function () {
        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null ) {
            if (MensajeError != "") {
                muestraMesanje(3,MensajeError);
            }
        }

    });

    function muestraMesanje(tipo, msj) {

        $("#msjContainer").html('');

        if (tipo == 1) {
            $("#msjContainer").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainer").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainer").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

    }
</script>

}

<style>

    .table-pager-footer > td {
        padding-top: 10px;
    }

        .table-pager-footer > td > a {
            background-color: #f5f5f5;
            border: 1px solid #ccc;
            border-radius: 3px;
            padding: 3px 7px;
        }

            .table-pager-footer > td > a:hover {
                background-color: #f0f0f0;
            }
</style>

adminlte/Views/TASEstudiante/TASEstudianteAsignacionMateriasEstudianteNuevo.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Asignar Materia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="box-body">
            <div id="msjContainerPartialView"></div>
            <div class="form-group">
                @Html.Label("Materia")
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-question"></i>
                    </div>
                    @Html.DropDownList("Materia", new SelectList(@ViewBag.ltTASMateria as System.Collections.IEnumerable), "Materia", new { @class = "form-control controlar" })

                </div>
            </div>

            <div class="form-group">
                @Html.Label("Grupo")
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-comment-o"></i>
                    </div>
                    @Html.DropDownList("Grupo", new SelectList(@ViewBag.ltTASGrupo as System.Collections.IEnumerable) as SelectList, "Grupo", new { @class = "form-control controlar" })

                </div>
            </div>

            @Html.Hidden((string)ViewBag.EstudianteCI)

        </div>

        <div class="modal-footer">
            <span id="progress" class="text-center" style="display: none;">

                Wait..
            </span>

            <input class="btn btn-primary" type="submit" value="Aceptar" />
            <button class="btn btn-warning" data-dismiss="modal" style="">
                Cerrar
            </button>
        </div>

    </div>
}

@*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/lib")*@

<style>
    .form-horizontal .form-group {
        margin-right: 0 !important;
    }
</style>

@*@Scripts.Render("~/bundles/jquery")*@
<script type="text/javascript">


    $(document).ready(function () {

        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null) {
            if (MensajeError != "") {
                muestraMesanje(3, MensajeError);
            }
        }
    })

    function muestraMesanje(tipo, msj) {

        $("#msjContainerPartialView").html('');

        if (tipo == 1) {
            $("#msjContainerPartialView").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainerPartialView").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainerPartialView").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

    }

</script>

adminlte/Views/TASEstudiante/TASEstudianteLista.cshtml
@model IEnumerable<adminlte.TASEstudianteService.TASEstudianteEntity>

@{
    ViewBag.Title = "TASEstudianteLista";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebGrid grid = new WebGrid(Model, // source
                                null, // columnNames
                                null, // defaultSort
                                50,   // rowsPerPage
                                true, // canPage
                                true, // canSort
                                null, // ajaxUpdateContainerId
                                null, // ajaxUpdateCallback
                                null, // fieldNamePrefix
                                null, // pageFieldName
                                null, // selectionFieldName
                                null, // sortFieldName
                                null);// sortDirectionFieldName
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Estudiante</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Estudiante</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content table-responsive">
        <!-- Default box -->
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title">CIAC TAS</h3>
            </div>
            <!-- /.box-header -->
            @*<div class="col-sm-12">
                    @Html.ActionLink(" ", "ASACuestionarioPregunta", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>*@
            <!-- form start -->
            @*<form role="form">*@
        <div class="box-body">
            <p>
                @Html.ActionLink(" ", "TASEstudianteNuevo", null, new { @class = "glyphicon glyphicon-plus ", style = "font-size:20px;" })
            </p>
            <br />
            @grid.GetHtml(
                    tableStyle: "table table-bordered",
                    headerStyle: "header",
                    alternatingRowStyle: "alt",
                    //tableStyle: "gridtable",
                    //headerStyle: "gridtable-header",
                    //alternatingRowStyle: "gridtable-alt",
                    footerStyle: "table-pager-footer",
                    columns: new[] {
                        //grid.Column("TipoDoc"),
                       // grid.Column("SubCompania"),
                        grid.Column("EstudianteCI"),
                        grid.Column("Grupo"),
                        grid.Column("Nombre1", "Nombre"),
                        grid.Column("Apellido1", "Apellido"),
                        //grid.Column("Estado"),


                        grid.Column("",
                                    header:"Acciones",
                                    format:@<text>
            @Html.ActionLink(" ", "TASEstudianteEditar", new {SubCompania = item.SubCompania, EstudianteCI=item.EstudianteCI },new {@class = "glyphicon glyphicon-edit",style = "font-size:15px;"})
                                    </text>
)
})
        </div>
            <!-- /.box-body -->
            @*</form>*@

        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<style>

    .table-pager-footer > td {
        padding-top: 10px;
    }

        .table-pager-footer > td > a {
            background-color: #f5f5f5;
            border: 1px solid #ccc;
            border-radius: 3px;
            padding: 3px 7px;
        }

            .table-pager-footer > td > a:hover {
                background-color: #f0f0f0;
            }
</style>