adminlte/Controllers/TASModuloController.cs
using adminlte.TASModuloService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace adminlte.Controllers
{
    public class TASModuloController : BaseController
    {
        // GET: TASModulo
        public ActionResult TASModuloLista()
        {
            TASModuloInterfaceClient TASModulo = new TASModuloInterfaceClient();
            var ltTASModulo = TASModulo.WebTASModuloSeleccionarTodo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            return View(ltTASModulo);
        }

        [HttpGet]
        public ActionResult TASModuloNuevo(string MensajeError = "")
        {
            TASModuloInterfaceClient TASModulo = new TASModuloInterfaceClient();
            TASModuloSet setTASModulo = TASModulo.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            ViewBag.MensajeError = MensajeError;

            return View(setTASModulo);
        }

        [HttpPost]
        public ActionResult TASModuloNuevo(TASModuloSet setTASModulo)
        {
            long NumError = 0;
            string Modulo = string.Empty;
            string MensajeError = string.Empty;

            TASModuloInterfaceClient TASModulo = new TASModuloInterfaceClient();

            if (setTASModulo.ltTASModulo != null)
            {
                TASModuloEntity etTASModulo = setTASModulo.ltTASModulo.First();
                if (etTASModulo.Modulo == null || etTASModulo.Modulo == "")
                {
                    NumError = 1;
                    MensajeError += "Debe ingresar un Modulo. ";
                }

                if (NumError == 0)
                {
                    TASModuloSet setTASModuloNuevo = TASModulo.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                    TASModuloEntity etTASModuloNuevo = setTASModuloNuevo.ltTASModulo.First();
                    etTASModuloNuevo.SubCompania = (string)Session["SesionSubCompania"];
                    etTASModuloNuevo.Modulo = etTASModulo.Modulo;
                    etTASModuloNuevo.Descripcion = etTASModulo.Descripcion == null ? "" : etTASModulo.Descripcion;
                    etTASModuloNuevo.Observacion = etTASModulo.Observacion == null ? "" : etTASModulo.Observacion;

                    etTASModuloNuevo.UEstado = TASModuloService.Estado.Added;
                    Modulo = etTASModulo.Modulo;
                    NumError = TASModulo.WebGuardar(setTASModuloNuevo, true, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                }
            }
            else
            {
                NumError = 1;
                MensajeError = "Ocurrio un error al intentar guardar. Intente nuevamente.";
            }

            if (NumError == 0)
            {
                return RedirectToAction("TASModuloEditar", new { SubCompania = (string)Session["SesionSubCompania"], Modulo = Modulo });
            }
            else
            {
                ViewBag.MensajeError = MensajeError;
                return View(setTASModulo);
            }

        }

        [HttpGet]
        public ActionResult TASModuloEditar(string SubCompania, string Modulo, string MensajeError = "")
        {
            TASModuloInterfaceClient TASModulo = new TASModuloInterfaceClient();
            TASModuloSet setTASModulo = new TASModuloSet();
            setTASModulo = TASModulo.WebSeleccionar(SubCompania, Modulo, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            ViewBag.MensajeError = MensajeError;

            return View(setTASModulo);
        }

        [HttpPost]
        public ActionResult TASModuloEditar(TASModuloSet setTASModulo)
        {
            long NumError = 0;
            string Modulo = string.Empty;
            string MensajeError = string.Empty;

            TASModuloInterfaceClient TASModulo = new TASModuloInterfaceClient();

            if (setTASModulo.ltTASModulo != null)
            {
                TASModuloEntity etTASModulo = setTASModulo.ltTASModulo.First();
                if (etTASModulo.Modulo == null || etTASModulo.Modulo == "")
                {
                    NumError = 1;
                    MensajeError += "Debe existir un Modulo. ";
                }

                if (NumError == 0)
                {
                    TASModuloSet setTASModuloEdit = TASModulo.WebSeleccionar((string)Session["SesionSubCompania"], etTASModulo.Modulo, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                    TASModuloEntity etTASModuloEdit = setTASModuloEdit.ltTASModulo.First();
                    //CodigoTAS Same as EstudianteCI
                    etTASModuloEdit.Descripcion = etTASModulo.Descripcion == null ? "" : etTASModulo.Descripcion;
                    etTASModuloEdit.Observacion = etTASModulo.Observacion == null ? "" : etTASModulo.Observacion;

                    etTASModuloEdit.UEstado = TASModuloService.Estado.Modified;
                    Modulo = etTASModulo.Modulo;
                    NumError = TASModulo.WebGuardar(setTASModuloEdit, false, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                }
            }
            else
            {
                NumError = 1;
                MensajeError = "Ocurrio un error al intentar guardar. Intente nuevamente.";
            }

            if (NumError == 0)
            {
                return RedirectToAction("TASModuloLista");
            }
            else
            {
                ViewBag.MensajeError = MensajeError;
                return View(setTASModulo);
            }
        }
    }
}

adminlte/Views/TASModulo/TASModuloEditar.cshtml
@model adminlte.TASModuloService.TASModuloSet

@{
    ViewBag.Title = "TASModuloEditar";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Modulo</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Modulo</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div id="msjContainer"></div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @*<form action="@Url.Action("TASModuloEditar","TASModulo", new {ModuloCI = Model.ltTASModulo[0].ModuloCI })" method="post" role="form" enctype="multipart/form-data">*@

                <div class="box-header with-border">
                    <h3 class="box-title">CIAC TAS</h3>
                </div>
                <!-- /.box-header -->
                <div class="col-sm-12">
                    @Html.ActionLink(" ", "TASModuloLista", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>
                <!-- form start -->
                @*<form role="form">*@
                <div class="box-body table-responsive">

                    <div class="form-group">
                        @Html.Label("Modulo")
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-users"></i>
                            </div>
                            @Html.TextBoxFor(model => model.ltTASModulo[0].Modulo, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
                            @*@Html.DropDownListFor(model => model.ltTASModulo[0].Observacion, new SelectList(@ViewBag.ltASAModuloPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].ModuloPregunta), "ModuloPregunta", new { @class = "form-control controlar" })*@
                            @Html.ValidationMessageFor(model => model.ltTASModulo[0].Modulo, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ltTASModulo[0].Modulo)
                        </div>
                        <!-- /.input group -->
                    </div>

                    <div class="form-group">
                        @Html.Label("Descripcion")
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-file-text"></i>
                            </div>
                            @Html.TextAreaFor(model => model.ltTASModulo[0].Descripcion, new { @class = "form-control" })
                            @*@Html.DropDownListFor(model => model.ltTASModulo[0].Observacion, new SelectList(@ViewBag.ltASAModuloPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].ModuloPregunta), "ModuloPregunta", new { @class = "form-control controlar" })*@
                            @Html.ValidationMessageFor(model => model.ltTASModulo[0].Descripcion, "", new { @class = "text-danger" })
                            @*<input type="number" class="form-control">*@
                        </div>
                        <!-- /.input group -->
                    </div>

                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                </div>
                @*</form>*@
                @*</form>*@
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@section scripts
{

    <script type="text/javascript">

     $(document).ready(function () {
        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null ) {
            if (MensajeError != "") {
                muestraMesanje(3,MensajeError);
            }
        }
    });

    function muestraMesanje(tipo, msj) {

        $("#msjContainer").html('');

        if (tipo == 1) {
            $("#msjContainer").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainer").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainer").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

    }
    </script>

}

adminlte/Views/TASModulo/TASModuloLista.cshtml
@model IEnumerable<adminlte.TASModuloService.TASModuloEntity>

@{
    ViewBag.Title = "TASModuloLista";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebGrid grid = new WebGrid(Model, // source
                                null, // columnNames
                                null, // defaultSort
                                50,   // rowsPerPage
                                true, // canPage
                                true, // canSort
                                null, // ajaxUpdateContainerId
                                null, // ajaxUpdateCallback
                                null, // fieldNamePrefix
                                null, // pageFieldName
                                null, // selectionFieldName
                                null, // sortFieldName
                                null);// sortDirectionFieldName
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Modulo</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Modulo</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content table-responsive">
        <!-- Default box -->
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title">CIAC TAS</h3>
            </div>
            <!-- /.box-header -->
            @*<div class="col-sm-12">
                    @Html.ActionLink(" ", "ASACuestionarioPregunta", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>*@
            <!-- form start -->
            @*<form role="form">*@
            <div class="box-body">
                <p>
                    @Html.ActionLink(" ", "TASModuloNuevo", null, new { @class = "glyphicon glyphicon-plus ", style = "font-size:20px;" })
                </p>
                <br />
                @grid.GetHtml(
                        tableStyle: "table table-bordered",
                        headerStyle: "header",
                        alternatingRowStyle: "alt",
                        //tableStyle: "gridtable",
                        //headerStyle: "gridtable-header",
                        //alternatingRowStyle: "gridtable-alt",
                        footerStyle: "table-pager-footer",
                        columns: new[] {
                            //grid.Column("TipoDoc"),
                           // grid.Column("SubCompania"),
                            grid.Column("Modulo"),
                            //grid.Column("Estado"),


                            grid.Column("",
                                        header:"Acciones",
                                        format:@<text>
        @Html.ActionLink(" ", "TASModuloEditar", new {SubCompania = item.SubCompania, Modulo=item.Modulo },new {@class = "glyphicon glyphicon-edit",style = "font-size:15px;"})
                                        </text>
)
})
            </div>
            <!-- /.box-body -->
            @*</form>*@

        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<style>

    .table-pager-footer > td {
        padding-top: 10px;
    }

        .table-pager-footer > td > a {
            background-color: #f5f5f5;
            border: 1px solid #ccc;
            border-radius: 3px;
            padding: 3px 7px;
        }

            .table-pager-footer > td > a:hover {
                background-color: #f0f0f0;
            }
</style>

adminlte/Views/TASModulo/TASModuloNuevo.cshtml
@model adminlte.TASModuloService.TASModuloSet

@{
    ViewBag.Title = "TASModuloNuevo";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Modulo</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Modulo</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div id="msjContainer"></div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @*<form action="@Url.Action("TASModuloNuevo","TASModulo", new {ModuloCI = Model.ltTASModulo[0].ModuloCI })" method="post" role="form" enctype="multipart/form-data">*@

                <div class="box-header with-border">
                    <h3 class="box-title">CIAC TAS</h3>
                </div>
                <!-- /.box-header -->
                <div class="col-sm-12">
                    @Html.ActionLink(" ", "TASModuloLista", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>
                <!-- form start -->
                @*<form role="form">*@
                <div class="box-body table-responsive">

                    <div class="form-group">
                        @Html.Label("Modulo")
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-users"></i>
                            </div>
                            @Html.TextBoxFor(model => model.ltTASModulo[0].Modulo, new { @class = "form-control" })
                            @*@Html.DropDownListFor(model => model.ltTASModulo[0].Observacion, new SelectList(@ViewBag.ltASAModuloPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].ModuloPregunta), "ModuloPregunta", new { @class = "form-control controlar" })*@
                            @Html.ValidationMessageFor(model => model.ltTASModulo[0].Modulo, "", new { @class = "text-danger" })
                            @*<input type="number" class="form-control">*@
                        </div>
                        <!-- /.input group -->
                    </div>


                    <div class="form-group">
                        @Html.Label("Descripcion")
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-file-text"></i>
                            </div>
                            @Html.TextAreaFor(model => model.ltTASModulo[0].Descripcion, new { @class = "form-control" })
                            @*@Html.DropDownListFor(model => model.ltTASModulo[0].Observacion, new SelectList(@ViewBag.ltASAModuloPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].ModuloPregunta), "ModuloPregunta", new { @class = "form-control controlar" })*@
                            @Html.ValidationMessageFor(model => model.ltTASModulo[0].Descripcion, "", new { @class = "text-danger" })
                            @*<input type="number" class="form-control">*@
                        </div>
                        <!-- /.input group -->
                    </div>

                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                </div>
                @*</form>*@
                @*</form>*@
            }
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@section scripts
{

    <script type="text/javascript">

     $(document).ready(function () {
        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null ) {
            if (MensajeError != "") {
                muestraMesanje(3,MensajeError);
            }
        }

    });

    function muestraMesanje(tipo, msj) {

        $("#msjContainer").html('');

        if (tipo == 1) {
            $("#msjContainer").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainer").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainer").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

    }
    </script>

}