adminlte/Controllers/AdminCatalogoMensualidadController.cs
using adminlte.AdminCatalogoMensualidadService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace adminlte.Controllers
{
    public class AdminCatalogoMensualidadController : BaseController
    {
        // GET: AdminCatalogoMensualidad
        public ActionResult AdminCatalogoMensualidadLista()
        {
            AdminCatalogoMensualidadInterfaceClient AdminCatalogoMensualidad = new AdminCatalogoMensualidadInterfaceClient();
            List<AdminCatalogoMensualidadEntity> ltAdminCatalogoMensualidad = AdminCatalogoMensualidad.WebAdminCatalogoMensualidadSeleccionarTodo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            return View(ltAdminCatalogoMensualidad);
        }

        [HttpGet]
        public ActionResult AdminCatalogoMensualidadNuevo(string MensajeError = "")
        {
            AdminCatalogoMensualidadInterfaceClient AdminCatalogoMensualidad = new AdminCatalogoMensualidadInterfaceClient();
            AdminCatalogoMensualidadSet setAdminCatalogoMensualidad = AdminCatalogoMensualidad.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            ViewBag.MensajeError = MensajeError;

            return View(setAdminCatalogoMensualidad);
        }

        [HttpPost]
        public ActionResult AdminCatalogoMensualidadNuevo(AdminCatalogoMensualidadSet setAdminCatalogoMensualidad)
        {
            string Mensualidad = string.Empty;
            long NumError = 0;
            string MensajeError = string.Empty;
            AdminCatalogoMensualidadInterfaceClient AdminCatalogoMensualidad = new AdminCatalogoMensualidadInterfaceClient();

            if (setAdminCatalogoMensualidad.ltAdminCatalogoMensualidad != null)
            {
                AdminCatalogoMensualidadEntity etAdminCatalogoMensualidad = setAdminCatalogoMensualidad.ltAdminCatalogoMensualidad.First();
                if (etAdminCatalogoMensualidad.Mensualidad != "")
                {
                    AdminCatalogoMensualidadSet setAdminCatalogoMensualidadNuevo = AdminCatalogoMensualidad.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                    AdminCatalogoMensualidadEntity etAdminCatalogoMensualidadNuevo = setAdminCatalogoMensualidadNuevo.ltAdminCatalogoMensualidad.First();

                    etAdminCatalogoMensualidadNuevo.Mensualidad = etAdminCatalogoMensualidad.Mensualidad;
                    etAdminCatalogoMensualidadNuevo.Descripcion = etAdminCatalogoMensualidad.Descripcion == null ? "" : etAdminCatalogoMensualidad.Descripcion;
                    etAdminCatalogoMensualidadNuevo.UEstado = AdminCatalogoMensualidadService.Estado.Added;
                    Mensualidad = etAdminCatalogoMensualidad.Mensualidad;

                    NumError = AdminCatalogoMensualidad.WebGuardar(setAdminCatalogoMensualidadNuevo, true, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                    
                    if (NumError != 0)
                    {
                        MensajeError = "Error al  guardar los datos en el servidor.";
                    }
                }
                else
                {
                    NumError = 1;
                    MensajeError = "La mensualidad es un campo obligatorio.";
                }
            }
            else
            {
                NumError = 1;
                MensajeError = "Hubo un error al mandar a guardar los datos.";
            }

            if (NumError == 0)
            {
                //return RedirectToAction("AdminCatalogoMensualidadEditar", new { Mensualidad = Mensualidad });
                return RedirectToAction("AdminCatalogoMensualidadLista");
            }
            else
            {
                ViewBag.MensajeError = MensajeError;
                return View(setAdminCatalogoMensualidad);
            }

        }

        //[HttpGet]
        //public ActionResult AdminCatalogoMensualidadEditar(string Mensualidad, string MensajeError = "")
        //{
        //    AdminCatalogoMensualidadInterfaceClient AdminCatalogoMensualidad = new AdminCatalogoMensualidadInterfaceClient();
        //    AdminCatalogoMensualidadSet setAdminCatalogoMensualidad = new AdminCatalogoMensualidadSet();

        //    setAdminCatalogoMensualidad = AdminCatalogoMensualidad.WebSeleccionar((string)Session["SesionSubCompania"], Mensualidad, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
        //    ViewBag.MensajeError = MensajeError;

        //    return View(setAdminCatalogoMensualidad);
        //}
        //[HttpPost]
        //public ActionResult AdminCatalogoMensualidadEditar(string Mensualidad, AdminCatalogoMensualidadSet setAdminCatalogoMensualidadForm)
        //{
        //    long NumError = 0;
        //    string MensajeError = string.Empty;
        //    AdminCatalogoMensualidadInterfaceClient AdminCatalogoMensualidad = new AdminCatalogoMensualidadInterfaceClient();
        //    AdminCatalogoMensualidadEntity etAdminCatalogoMensualidadForm = setAdminCatalogoMensualidadForm.ltAdminCatalogoMensualidad.First();
        //    if (etAdminCatalogoMensualidadForm != null)
        //    {
        //        AdminCatalogoMensualidadSet setAdminCatalogoMensualidad = AdminCatalogoMensualidad.WebSeleccionar((string)Session["SesionSubCompania"], Mensualidad, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
        //        AdminCatalogoMensualidadEntity etAdminCatalogoMensualidad = setAdminCatalogoMensualidad.ltAdminCatalogoMensualidad.First();

        //        etAdminCatalogoMensualidad.Observacion = etAdminCatalogoMensualidadForm.Observacion == null ? "" : etAdminCatalogoMensualidadForm.Observacion;
        //        etAdminCatalogoMensualidad.UEstado = AdminCatalogoMensualidadService.Estado.Modified;

        //        NumError = AdminCatalogoMensualidad.WebGuardar(setAdminCatalogoMensualidad, false, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
        //        if (NumError != 0)
        //        {
        //            MensajeError = "Hubo un error al guardar en el servidor";
        //        }
        //    }
        //    else
        //    {
        //        NumError = 1;
        //        MensajeError = "El formulario contiene un error.";
        //    }            

        //    if (NumError == 0)
        //    {
        //        return RedirectToAction("ASACuestionarioListaPregunta");
        //    }
        //    else
        //    {
        //        return RedirectToAction("AdminCatalogoMensualidadEditar", new { Mensualidad = Mensualidad, MensajeError = MensajeError });
        //    }
        //}
        //public ActionResult AdminCatalogoMensualidadEliminar(string Mensualidad, string MensajeError = "")
        //{
        //    AdminCatalogoMensualidadInterfaceClient AdminCatalogoMensualidad = new AdminCatalogoMensualidadInterfaceClient();
        //    AdminCatalogoMensualidadSet setAdminCatalogoMensualidad = new AdminCatalogoMensualidadSet();

        //    setAdminCatalogoMensualidad = AdminCatalogoMensualidad.WebSeleccionar((string)Session["SesionSubCompania"], Mensualidad, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                        
        //    ViewBag.MensajeError = MensajeError;

        //    return View(setAdminCatalogoMensualidad);
        //}
        //[HttpPost, ActionName("AdminCatalogoMensualidadEliminar")]
        //public ActionResult AdminCatalogoMensualidadEliminarConfirmacion(string Mensualidad)
        //{
        //    long NumError = 0;
        //    string MensajeError = string.Empty;
        //    AdminCatalogoMensualidadInterfaceClient AdminCatalogoMensualidad = new AdminCatalogoMensualidadInterfaceClient();

        //    if (Mensualidad != 0)
        //    {
        //        AdminCatalogoMensualidadSet setAdminCatalogoMensualidadBorrar = AdminCatalogoMensualidad.WebSeleccionar(Mensualidad, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);

        //        NumError = AdminCatalogoMensualidad.WebEliminar(setAdminCatalogoMensualidadBorrar, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
        //        if (NumError != 0)
        //        {
        //            MensajeError = "Error al eliminar la pregunta.";
        //        }
        //    }
        //    else
        //    {
        //        NumError = 1;
        //        MensajeError = "Numero de pregunta invalida para borrar.";
        //    }

        //    if (NumError == 0)
        //    {
        //        return RedirectToAction("ASACuestionarioListaPregunta");
        //    }
        //    else
        //    {
        //        return RedirectToAction("AdminCatalogoMensualidadEliminar", new { Mensualidad = Mensualidad, MensajeError = MensajeError });
        //    }
        //}
    }
}

adminlte/Views/AdminCatalogoMensualidad/AdminCatalogoMensualidadLista.cshtml
@model IEnumerable<adminlte.AdminCatalogoMensualidadService.AdminCatalogoMensualidadEntity>

@{
    ViewBag.Title = "AdminCatalogoMensualidadLista";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebGrid grid = new WebGrid(Model, // source
                                null, // columnNames
                                null, // defaultSort
                                50,   // rowsPerPage
                                true, // canPage
                                true, // canSort
                                null, // ajaxUpdateContainerId
                                null, // ajaxUpdateCallback
                                null, // fieldNamePrefix
                                null, // pageFieldName
                                null, // selectionFieldName
                                null, // sortFieldName
                                null);// sortDirectionFieldName
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Catalogo Mensualidad</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Catalogo Mensualidades</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content table-responsive">
        <!-- Default box -->
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title">CIAC TAS</h3>
            </div>
            <!-- /.box-header -->
            @*<div class="col-sm-12">
                    @Html.ActionLink(" ", "AdminCatalogoMensualidadNuevo", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>*@
            <!-- form start -->
            @*<form role="form">*@
        <div class="box-body table-responsive">
            <h4>Catalogo Mensualidad</h4>
            <p>
                @Html.ActionLink(" ", "AdminCatalogoMensualidadNuevo", null, new { @class = "glyphicon glyphicon-plus ", style = "font-size:20px;" })
            </p>
            <br />
            @grid.GetHtml(
                    tableStyle: "table table-bordered",
                    headerStyle: "header",
                    alternatingRowStyle: "alt",
                    //tableStyle: "gridtable",
                    //headerStyle: "gridtable-header",
                    //alternatingRowStyle: "gridtable-alt",
                    footerStyle: "table-pager-footer",
                    columns: new[] {
                        //grid.Column("TipoDoc"),
                       // grid.Column("SubCompania"),
                        grid.Column("Mensualidad")
                        //grid.Column("Pregunta"),
                        //grid.Column("GrupoPregunta"),
                        //grid.Column("ClaseOri"),
                        //grid.Column("Estado"),


                            @*grid.Column("",
                                                        header:"Acciones",
                                                        format:@<text>
                        @Html.ActionLink(" ", "AdminCatalogoMensualidadEditar", new { EstudianteCI=item.EstudianteCI },new {@class = "glyphicon glyphicon-edit",style = "font-size:15px;"})
                                                        </text>
                           )*@
})
        </div>
            <!-- /.box-body -->
            @*</form>*@

        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<style>

    .table-pager-footer > td {
        padding-top: 10px;
    }

        .table-pager-footer > td > a {
            background-color: #f5f5f5;
            border: 1px solid #ccc;
            border-radius: 3px;
            padding: 3px 7px;
        }

            .table-pager-footer > td > a:hover {
                background-color: #f0f0f0;
            }
</style>

adminlte/Views/AdminCatalogoMensualidad/AdminCatalogoMensualidadNuevo.cshtml
@model adminlte.AdminCatalogoMensualidadService.AdminCatalogoMensualidadSet

@{
    ViewBag.Title = "AdminCatalogoMensualidadEditar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Catalogo Mensualidad</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Catalogo Mensualidades</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div id="msjContainer"></div>
            <form action="@Url.Action("AdminCatalogoMensualidadNuevo","AdminCatalogoMensualidad")" method="post" role="form">

                <div class="box-header with-border">
                    <h3 class="box-title">CIAC TAS</h3>
                </div>
                <!-- /.box-header -->
                <div class="col-sm-12">
                    @Html.ActionLink(" ", "AdminCatalogoMensualidadLista", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>
                <!-- form start -->
                @*<form role="form">*@
            <div class="box-body table-responsive">

                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.Label("Mensualidad")
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-users"></i>
                        </div>
                        @Html.TextBoxFor(model => model.ltAdminCatalogoMensualidad[0].Mensualidad, new { @class = "form-control" })
                        @*@Html.DropDownListFor(model => model.ltAdminCatalogoMensualidad[0].Observacion, new SelectList(@ViewBag.ltASAGrupoPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].GrupoPregunta), "GrupoPregunta", new { @class = "form-control controlar" })*@
                        @Html.ValidationMessageFor(model => model.ltAdminCatalogoMensualidad[0].Mensualidad, "", new { @class = "text-danger" })
                        @*<input type="number" class="form-control">*@
                    </div>
                    <!-- /.input group -->
                </div>

                <div class="form-group">
                    @Html.Label("Observacion (Opcional)")
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-users"></i>
                        </div>
                        @Html.TextAreaFor(model => model.ltAdminCatalogoMensualidad[0].Observacion, new { @class = "form-control" })
                        @*@Html.DropDownListFor(model => model.ltAdminCatalogoMensualidad[0].Observacion, new SelectList(@ViewBag.ltASAGrupoPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].GrupoPregunta), "GrupoPregunta", new { @class = "form-control controlar" })*@
                        @Html.ValidationMessageFor(model => model.ltAdminCatalogoMensualidad[0].Observacion, "", new { @class = "text-danger" })
                        @*<input type="number" class="form-control">*@
                    </div>
                    <!-- /.input group -->
                </div>

            </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                </div>
                @*</form>*@
            </form>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content" style="padding-top:2%;">
            <div id='myModalContent' style="padding-left:5%;"></div>
        </div>
    </div>
</div>

@*@Scripts.Render("~/Scripts/adminlte/js/modal.js")*@
<script src="~/Scripts/adminlte/components/jquery/dist/jquery.min.js"></script>
<script src="~/Scripts/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="~/Scripts/adminlte/js/modal.js"></script>

@section scripts
{

    <script type="text/javascript">

     $(document).ready(function () {
        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null ) {
            if (MensajeError != "") {
                muestraMesanje(3,MensajeError);
            }
        }

    });

    function muestraMesanje(tipo, msj) {

        $("#msjContainer").html('');

        if (tipo == 1) {
            $("#msjContainer").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainer").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainer").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

    }
    </script>

}