adminlte/Controllers/AdminCatalogoTextoController.cs
using adminlte.AdminCatalogoTextoService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace adminlte.Controllers
{
    public class AdminCatalogoTextoController : BaseController
    {
        // GET: AdminCatalogoTexto
        public ActionResult AdminCatalogoTextoLista()
        {
            AdminCatalogoTextoInterfaceClient AdminCatalogoTexto = new AdminCatalogoTextoInterfaceClient();
            List<AdminCatalogoTextoEntity> ltAdminCatalogoTexto = AdminCatalogoTexto.WebAdminCatalogoTextoSeleccionarTodo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            return View(ltAdminCatalogoTexto);
        }

        [HttpGet]
        public ActionResult AdminCatalogoTextoNuevo(string MensajeError = "")
        {
            AdminCatalogoTextoInterfaceClient AdminCatalogoTexto = new AdminCatalogoTextoInterfaceClient();
            AdminCatalogoTextoSet setAdminCatalogoTexto = AdminCatalogoTexto.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);

            ViewBag.MensajeError = MensajeError;

            return View(setAdminCatalogoTexto);
        }

        [HttpPost]        
        public ActionResult AdminCatalogoTextoNuevo(AdminCatalogoTextoSet setAdminCatalogoTexto)
        {
            string Texto = string.Empty;
            long NumError = 0;
            string MensajeError = string.Empty;
            AdminCatalogoTextoInterfaceClient AdminCatalogoTexto = new AdminCatalogoTextoInterfaceClient();

            if (setAdminCatalogoTexto.ltAdminCatalogoTexto != null)
            {
                AdminCatalogoTextoEntity etAdminCatalogoTexto = setAdminCatalogoTexto.ltAdminCatalogoTexto.First();
                if (etAdminCatalogoTexto.Texto != "")
                {
                    AdminCatalogoTextoSet setAdminCatalogoTextoNuevo = AdminCatalogoTexto.WebNuevo((string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                    AdminCatalogoTextoEntity etAdminCatalogoTextoNuevo = setAdminCatalogoTextoNuevo.ltAdminCatalogoTexto.First();

                    etAdminCatalogoTextoNuevo.SubCompania = (string)Session["SesionSubCompania"];
                    etAdminCatalogoTextoNuevo.Texto = etAdminCatalogoTexto.Texto;
                    etAdminCatalogoTextoNuevo.MontoSugerido = etAdminCatalogoTexto.MontoSugerido;
                    etAdminCatalogoTextoNuevo.Descripcion = etAdminCatalogoTexto.Descripcion == null ? "" : etAdminCatalogoTexto.Descripcion;
                    etAdminCatalogoTextoNuevo.UEstado = AdminCatalogoTextoService.Estado.Added;
                    Texto = etAdminCatalogoTexto.Texto;

                    NumError = AdminCatalogoTexto.WebGuardar(setAdminCatalogoTextoNuevo, true, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);

                    if (NumError != 0)
                    {
                        MensajeError = "Error al  guardar los datos en el servidor.";
                    }
                }
                else
                {
                    NumError = 1;
                    MensajeError = "Texto es un campo obligatorio.";
                }
            }
            else
            {
                NumError = 1;
                MensajeError = "Hubo un error al mandar a guardar los datos.";
            }

            if (NumError == 0)
            {
                //return RedirectToAction("AdminCatalogoTextoEditar", new { Texto = Texto });
                return RedirectToAction("AdminCatalogoTextoLista");
            }
            else
            {
                ViewBag.MensajeError = MensajeError;
                return View(setAdminCatalogoTexto);
            }

        }

        [HttpGet]
        public ActionResult AdminCatalogoTextoEditar(string Texto, string MensajeError = "")
        {
            AdminCatalogoTextoInterfaceClient AdminCatalogoTexto = new AdminCatalogoTextoInterfaceClient();
            AdminCatalogoTextoSet setAdminCatalogoTexto = AdminCatalogoTexto.WebSeleccionar((string)Session["SesionSubCompania"], Texto, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
            ViewBag.MensajeError = MensajeError;

            return View(setAdminCatalogoTexto);
        }
        [HttpPost]
        public ActionResult AdminCatalogoTextoEditar(string Texto, AdminCatalogoTextoSet setAdminCatalogoTextoForm)
        {
            long NumError = 0;
            string MensajeError = string.Empty;
            AdminCatalogoTextoInterfaceClient AdminCatalogoTexto = new AdminCatalogoTextoInterfaceClient();
            AdminCatalogoTextoEntity etAdminCatalogoTextoForm = setAdminCatalogoTextoForm.ltAdminCatalogoTexto.First();
            if (etAdminCatalogoTextoForm != null)
            {
                AdminCatalogoTextoSet setAdminCatalogoTexto = AdminCatalogoTexto.WebSeleccionar((string)Session["SesionSubCompania"], Texto, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                AdminCatalogoTextoEntity etAdminCatalogoTexto = setAdminCatalogoTexto.ltAdminCatalogoTexto.First();

                etAdminCatalogoTexto.MontoSugerido = etAdminCatalogoTextoForm.MontoSugerido;
                etAdminCatalogoTexto.Observacion = etAdminCatalogoTextoForm.Observacion == null ? "" : etAdminCatalogoTextoForm.Observacion;
                etAdminCatalogoTexto.UEstado = AdminCatalogoTextoService.Estado.Modified;

                NumError = AdminCatalogoTexto.WebGuardar(setAdminCatalogoTexto, false, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
                if (NumError != 0)
                {
                    MensajeError = "Hubo un error al guardar en el servidor";
                }
            }
            else
            {
                NumError = 1;
                MensajeError = "El formulario contiene un error.";
            }

            if (NumError == 0)
            {
                return RedirectToAction("AdminCatalogoTextoLista");
            }
            else
            {
                return RedirectToAction("AdminCatalogoTextoEditar", new { Texto = Texto, MensajeError = MensajeError });
            }
        }
        //public ActionResult AdminCatalogoTextoEliminar(string Mensualidad, string MensajeError = "")
        //{
        //    AdminCatalogoTextoInterfaceClient AdminCatalogoTexto = new AdminCatalogoTextoInterfaceClient();
        //    AdminCatalogoTextoSet setAdminCatalogoTexto = new AdminCatalogoTextoSet();

        //    setAdminCatalogoTexto = AdminCatalogoTexto.WebSeleccionar((string)Session["SesionSubCompania"], Mensualidad, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);

        //    ViewBag.MensajeError = MensajeError;

        //    return View(setAdminCatalogoTexto);
        //}
        //[HttpPost, ActionName("AdminCatalogoTextoEliminar")]
        //public ActionResult AdminCatalogoTextoEliminarConfirmacion(string Mensualidad)
        //{
        //    long NumError = 0;
        //    string MensajeError = string.Empty;
        //    AdminCatalogoTextoInterfaceClient AdminCatalogoTexto = new AdminCatalogoTextoInterfaceClient();

        //    if (Mensualidad != 0)
        //    {
        //        AdminCatalogoTextoSet setAdminCatalogoTextoBorrar = AdminCatalogoTexto.WebSeleccionar(Mensualidad, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);

        //        NumError = AdminCatalogoTexto.WebEliminar(setAdminCatalogoTextoBorrar, (string)Session["Sesion"], (string)Session["SesionSubCompania"]);
        //        if (NumError != 0)
        //        {
        //            MensajeError = "Error al eliminar la pregunta.";
        //        }
        //    }
        //    else
        //    {
        //        NumError = 1;
        //        MensajeError = "Numero de pregunta invalida para borrar.";
        //    }

        //    if (NumError == 0)
        //    {
        //        return RedirectToAction("ASACuestionarioListaPregunta");
        //    }
        //    else
        //    {
        //        return RedirectToAction("AdminCatalogoTextoEliminar", new { Mensualidad = Mensualidad, MensajeError = MensajeError });
        //    }
        //}
    }
}

adminlte/Views/AdminCatalogoTexto/AdminCatalogoTextoEditar.cshtml
@model adminlte.AdminCatalogoTextoService.AdminCatalogoTextoSet

@{
    ViewBag.Title = "AdminCatalogoTextoEditar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Catalogo Texto</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Catalogo Texto</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div id="msjContainer"></div>
            <form action="@Url.Action("AdminCatalogoTextoEditar","AdminCatalogoTexto", new {Texto = Model.ltAdminCatalogoTexto[0].Texto })" method="post" role="form">

                <div class="box-header with-border">
                    <h3 class="box-title">CIAC TAS</h3>
                </div>
                <!-- /.box-header -->
                <div class="col-sm-12">
                    @Html.ActionLink(" ", "AdminCatalogoTextoLista", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>
                <!-- form start -->
                @*<form role="form">*@
            <div class="box-body table-responsive">

                @Html.AntiForgeryToken()

                <div class="form-group">
                    @*@Html.Label("Cantidad Preguntas")*@
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-users"> @Html.Label(Model.ltAdminCatalogoTexto[0].Texto.ToString(), new { htmlAttributes = new { @class = "form-control" } })</i>
                        </div>

                        @*@Html.ValidationMessageFor(model => model.ltASAPregunta[0].CantidadPregunta, "", new { @class = "text-danger" })*@
                        @*<input type="number" class="form-control">*@
                    </div>
                    <!-- /.input group -->
                </div>

                <div class="form-group">
                    @Html.Label("Monto Sugerido")
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-usd"></i>
                        </div>
                        @Html.EditorFor(model => model.ltAdminCatalogoTexto[0].MontoSugerido, new { htmlAttributes = new { @class = "form-control allownumericwithdecimal" } })
                        @Html.ValidationMessageFor(model => model.ltAdminCatalogoTexto[0].MontoSugerido, "", new { @class = "text-danger" })
                        @*<input type="number" class="form-control">*@
                        <span class="input-group-addon">,00</span>
                    </div>

                    <!-- /.input group -->
                </div>

                <div class="form-group">
                    @Html.Label("Observaciones")
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-users"></i>
                        </div>
                        @Html.TextAreaFor(model => model.ltAdminCatalogoTexto[0].Observacion, new { @class = "form-control" })
                        @*@Html.DropDownListFor(model => model.ltAdminCatalogoTexto[0].Observacion, new SelectList(@ViewBag.ltASAGrupoPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].GrupoPregunta), "GrupoPregunta", new { @class = "form-control controlar" })*@
                        @Html.ValidationMessageFor(model => model.ltAdminCatalogoTexto[0].Observacion, "", new { @class = "text-danger" })
                        @*<input type="number" class="form-control">*@
                    </div>
                    <!-- /.input group -->
                </div>

            </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                </div>
                @*</form>*@
            </form>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section scripts
{

    <script type="text/javascript">

     $(document).ready(function () {
        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null ) {
            if (MensajeError != "") {
                muestraMesanje(3,MensajeError);
            }
        }

    });

        $(".allownumericwithdecimal").on("keypress keyup blur", function (event) {
            //this.value = this.value.replace(/[^0-9\.]/g,'');
            $(this).val($(this).val().replace(/[^0-9\,]/g, ''));
            if ((event.which != 44 || $(this).val().indexOf(',') != -1) && (event.which < 48 || event.which > 57)) {
                event.preventDefault();
            }
        });

    function muestraMesanje(tipo, msj) {

        $("#msjContainer").html('');

        if (tipo == 1) {
            $("#msjContainer").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainer").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainer").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

    }
    </script>

}

adminlte/Views/AdminCatalogoTexto/AdminCatalogoTextoLista.cshtml
@model IEnumerable<adminlte.AdminCatalogoTextoService.AdminCatalogoTextoEntity>

@{
    ViewBag.Title = "AdminCatalogoTextoLista";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WebGrid grid = new WebGrid(Model, // source
                                null, // columnNames
                                null, // defaultSort
                                50,   // rowsPerPage
                                true, // canPage
                                true, // canSort
                                null, // ajaxUpdateContainerId
                                null, // ajaxUpdateCallback
                                null, // fieldNamePrefix
                                null, // pageFieldName
                                null, // selectionFieldName
                                null, // sortFieldName
                                null);// sortDirectionFieldName
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Catalogo Texto</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Catalogo Texto</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content table-responsive">
        <!-- Default box -->
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title">CIAC TAS</h3>
            </div>
            <!-- /.box-header -->
            @*<div class="col-sm-12">
                    @Html.ActionLink(" ", "AdminCatalogoTextoNuevo", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>*@
            <!-- form start -->
            @*<form role="form">*@
            <div class="box-body table-responsive">
                <h4>Catalogo Texto</h4>
                <p>
                    @Html.ActionLink(" ", "AdminCatalogoTextoNuevo", null, new { @class = "glyphicon glyphicon-plus ", style = "font-size:20px;" })
                </p>
                <br />
                @grid.GetHtml(
                        tableStyle: "table table-bordered",
                        headerStyle: "header",
                        alternatingRowStyle: "alt",
                        //tableStyle: "gridtable",
                        //headerStyle: "gridtable-header",
                        //alternatingRowStyle: "gridtable-alt",
                        footerStyle: "table-pager-footer",
                        columns: new[] {
                            //grid.Column("TipoDoc"),
                           // grid.Column("SubCompania"),
                            grid.Column("Texto"),
                            grid.Column("MontoSugerido"),
                            //grid.Column("GrupoPregunta"),
                            //grid.Column("ClaseOri"),
                            //grid.Column("Estado"),


                                grid.Column("",
                                                                    header:"Acciones",
                                                                    format:@<text>
                                    @Html.ActionLink(" ", "AdminCatalogoTextoEditar", new { Texto=item.Texto },new {@class = "glyphicon glyphicon-edit",style = "font-size:15px;"})
                                                                    </text>
                                       )
         })
            </div>
            <!-- /.box-body -->
            @*</form>*@

        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<style>

    .table-pager-footer > td {
        padding-top: 10px;
    }

        .table-pager-footer > td > a {
            background-color: #f5f5f5;
            border: 1px solid #ccc;
            border-radius: 3px;
            padding: 3px 7px;
        }

            .table-pager-footer > td > a:hover {
                background-color: #f0f0f0;
            }
</style>

adminlte/Views/AdminCatalogoTexto/AdminCatalogoTextoNuevo.cshtml
@model adminlte.AdminCatalogoTextoService.AdminCatalogoTextoSet

@{
    ViewBag.Title = "AdminCatalogoTextoNuevo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Admin
            <small>Catalogo Texto</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Admin</a></li>
            <li class="active">Catalogo Texto</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box box-primary">
            <div id="msjContainer"></div>
            <form action="@Url.Action("AdminCatalogoTextoNuevo","AdminCatalogoTexto")" method="post" role="form">

                <div class="box-header with-border">
                    <h3 class="box-title">CIAC TAS</h3>
                </div>
                <!-- /.box-header -->
                <div class="col-sm-12">
                    @Html.ActionLink(" ", "AdminCatalogoTextoLista", null, new { @class = "glyphicon glyphicon-circle-arrow-left ", style = "font-size:28px;" })
                </div>
                <!-- form start -->
                @*<form role="form">*@
            <div class="box-body table-responsive">

                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.Label("Texto")
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-users"></i>
                        </div>
                        @Html.TextBoxFor(model => model.ltAdminCatalogoTexto[0].Texto, new { @class = "form-control" })
                        @*@Html.DropDownListFor(model => model.ltAdminCatalogoTexto[0].Observacion, new SelectList(@ViewBag.ltASAGrupoPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].GrupoPregunta), "GrupoPregunta", new { @class = "form-control controlar" })*@
                        @Html.ValidationMessageFor(model => model.ltAdminCatalogoTexto[0].Texto, "", new { @class = "text-danger" })
                        @*<input type="number" class="form-control">*@
                    </div>
                    <!-- /.input group -->
                </div>

                <div class="form-group">
                    @Html.Label("Monto Sugerido")
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-usd"></i>
                        </div>
                        @Html.EditorFor(model => model.ltAdminCatalogoTexto[0].MontoSugerido, new { htmlAttributes = new { @class = "form-control allownumericwithdecimal" } })
                        @Html.ValidationMessageFor(model => model.ltAdminCatalogoTexto[0].MontoSugerido, "", new { @class = "text-danger" })
                        @*<input type="number" class="form-control">*@
                        <span class="input-group-addon">,00</span>
                    </div>

                    <!-- /.input group -->
                </div>

                <div class="form-group">
                    @Html.Label("Observacion (Opcional)")
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-users"></i>
                        </div>
                        @Html.TextAreaFor(model => model.ltAdminCatalogoTexto[0].Observacion, new { @class = "form-control" })
                        @*@Html.DropDownListFor(model => model.ltAdminCatalogoTexto[0].Observacion, new SelectList(@ViewBag.ltASAGrupoPregunta as System.Collections.IEnumerable, Model.ltASAPregunta[0].GrupoPregunta), "GrupoPregunta", new { @class = "form-control controlar" })*@
                        @Html.ValidationMessageFor(model => model.ltAdminCatalogoTexto[0].Observacion, "", new { @class = "text-danger" })
                        @*<input type="number" class="form-control">*@
                    </div>
                    <!-- /.input group -->
                </div>

            </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                </div>
                @*</form>*@
            </form>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content" style="padding-top:2%;">
            <div id='myModalContent' style="padding-left:5%;"></div>
        </div>
    </div>
</div>

@*@Scripts.Render("~/Scripts/adminlte/js/modal.js")*@
<script src="~/Scripts/adminlte/components/jquery/dist/jquery.min.js"></script>
<script src="~/Scripts/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="~/Scripts/adminlte/js/modal.js"></script>

@section scripts
{

    <script type="text/javascript">

     $(document).ready(function () {
        var MensajeError = '@ViewBag.MensajeError';
        if (MensajeError != null ) {
            if (MensajeError != "") {
                muestraMesanje(3,MensajeError);
            }
        }

     });

        $(".allownumericwithdecimal").on("keypress keyup blur", function (event) {
            //this.value = this.value.replace(/[^0-9\.]/g,'');
            $(this).val($(this).val().replace(/[^0-9\,]/g, ''));
            if ((event.which != 44 || $(this).val().indexOf(',') != -1) && (event.which < 48 || event.which > 57)) {
                event.preventDefault();
            }
        });

    function muestraMesanje(tipo, msj) {

        $("#msjContainer").html('');

        if (tipo == 1) {
            $("#msjContainer").append('<div class="alert alert-success alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;<strong>Operacion realizada exitosamente.</strong>&nbsp;' + msj + '</div>')
        } else if (tipo == 2) {
            $("#msjContainer").append('<div class="alert alert-danger alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;<strong>Error:</strong>' + msj + '</div>')
        } else if (tipo == 3) {
            $("#msjContainer").append('<div class="alert alert-warning alert-dismissable fade in"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>&nbsp;<strong>Atencion:&nbsp;</strong>' + msj + '</div>')
        }

    }
    </script>

}